### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by kpjVideo** [extigy/repo#1]
This is more of a question rather than an issue, however I have no other means to contact the developer.

I was simply wondering whether netKillUI is able to detect IPs (Through the ARP scan) that are outside the 192.168.xxx.xxx range. I've attempted to scan on a few networks that use the 10.230.xxx.xxx structure, and so far none have come up as detected in the list of devices.

Thanks!

**Comment by extigy** [comment]
Sorry for never replying to this. IIRC 192.168.xxx.xxx wasn't hard coded anywhere by me, but I didn't write the spoofing and scanning command line tools so perhaps they were where the limit was.

The UI app hasn't worked properly since iOS9 and I had a clean out of my repo. Since I won't be updating it for current and future iOS versions I have removed NetKillUI along with some other older iOS 8 tweaks. Due to this I have closed the Issue.
